### ISSUE TITLE
I have some questions

### ISSUE THREAD

**Issue by skzhang1** [qq456cvb/GrabCut#1]
Thank you very much for providing such excellent work . I was recently asked to implement this paper and would like to ask your implementation ideas. Do you start from 0 completely? What codes and documents are referenced when you implement them? Can you share them? I can't understand your code very well.

**Comment by qq456cvb** [comment]
I started from 0, except for the maxflow algorithm from https://vision.cs.uwaterloo.ca/code/ (while code is included in the repo). I followed what is described in the paper _“GrabCut” — Interactive Foreground Extraction using Iterated Graph Cuts_. and you will find functions like `assign_GMM_components()`,  `update_GMM_params()`, `estimate_segmentation()`, which corresponds the paper's pseudo code in figure 3.

**Comment by skzhang1** [comment]
I have no question now
